language: node_js
node_js:
- '10'
dist: xenial
services:
  - xvfb
before_install:
- gem install sass
- gem install compass

before_script:
- "export DISPLAY=:99.0"
- 'npm install -g bower grunt-cli karma'
- 'bower install'

script: grunt --force
