language: node_js

before_install:
- gem install sass
- gem install compass

node_js:
- '0.10'
services:
- xvfb

before_script:
- "export DISPLAY=:99.0"
- 'npm install -g bower grunt-cli karma'
- 'bower install'

script: grunt --force
